workspace:
  base: /drone
  path: /custombuild

pipeline:
  submod:
     image: plugins/git
     commands:
       - pwd
       - ls -la
       - cd /drone/custombuild/sources/meta-java
       - pwd
       - git submodule update --recursive
       - git submodule update --recursive --remote
       - ls -la
  build:
    image: tlwt/yoctodocker:latest
    secrets: [ GITHUB_TOKEN ]
    environment:
       - GIT_EMAIL=mail@tillwitt.de
       - GIT_NAME=Till Witt
       - Y_MACHINE=imx6ulevk
       - Y_DISTRO=fsl-imx-x11
       - Y_IMAGE=core-image-base
       - GITHUB_USER=tlwt
       - GITHUB_REPO=imx-x11-imx6ulevk
       - disable_release=1
  slack: # pushing out notification
    image: plugins/slack:latest
    channel: build-automation
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
branches: master
